name: Docker Image CI
on: push
jobs:
  build_and_publish:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - name: Build and push to GPR
      run: |
        docker login --username nalyDzzz --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . -t ghcr.io/nalyDzzz/to-do-list:latest
        docker push ghcr.io/nalyDzzz/to-do-list:latest
